packages:
  - packages/app/*
  - packages/sdk/*
  - packages/sdk/examples/*
  - packages/tests/*
  - packages/n8n-nodes-echo/
allowBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
