services:
  postgres:
    image: postgres:15
    container_name: echo-control-postgres-v2
    restart: unless-stopped
    environment:
      POSTGRES_DB: echo_control_v2
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: echo_password
    ports:
      - "5469:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U echo_user -d echo_control_v2"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 