#!/bin/bash
set -e

# Echo Local Development Setup
# Gets you from a fresh clone to a running local dev environment.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTROL_DIR="$ROOT_DIR/packages/app/control"
SERVER_DIR="$ROOT_DIR/packages/app/server"

echo ""
echo "=== Echo Local Development Setup ==="
echo ""

# ------------------------------------------------------------------
# 1. Check prerequisites
# ------------------------------------------------------------------

check_command() {
  if ! command -v "$1" &> /dev/null; then
    echo "ERROR: '$1' is required but not installed."
    echo "  $2"
    exit 1
  fi
}

check_command "node" "Install Node.js 18+: https://nodejs.org"
check_command "pnpm" "Install pnpm: npm install -g pnpm"
check_command "docker" "Install Docker: https://docs.docker.com/get-docker/"

# Check Docker is running
if ! docker info &> /dev/null 2>&1; then
  echo "ERROR: Docker daemon is not running. Please start Docker and try again."
  exit 1
fi

# Check docker compose
if docker compose version &> /dev/null 2>&1; then
  DOCKER_COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null 2>&1; then
  DOCKER_COMPOSE="docker-compose"
else
  echo "ERROR: 'docker compose' is required but not found."
  echo "  Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

echo "[1/5] Prerequisites OK (node, pnpm, docker, docker compose)"

# ------------------------------------------------------------------
# 2. Generate AUTH_SECRET
# ------------------------------------------------------------------

AUTH_SECRET_VALUE=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")

# ------------------------------------------------------------------
# 3. Create .env for echo-control (if missing)
# ------------------------------------------------------------------

if [ -f "$CONTROL_DIR/.env" ]; then
  echo "[2/5] packages/app/control/.env already exists, skipping"
else
  envsubst_control() {
    cat > "$CONTROL_DIR/.env" << CONTROLENV
# Echo Control - Local Development
# Generated by: pnpm setup

ECHO_CONTROL_APP_BASE_URL="http://localhost:3000"
API_KEY_PREFIX="echo_"

# Database (Docker container on port 5469)
DATABASE_URL="postgresql://echo_user:echo_password@localhost:5469/echo_control_v2?schema=public"

# Auth
AUTH_SECRET="$AUTH_SECRET_VALUE"

# OAuth providers - defaults work for local dev but won't actually authenticate.
# To test real OAuth login, register apps at:
#   Google: https://console.cloud.google.com/apis/credentials
#   GitHub: https://github.com/settings/developers
AUTH_GOOGLE_ID="placeholder-for-local-dev"
AUTH_GOOGLE_SECRET="placeholder-for-local-dev"
AUTH_GITHUB_ID="placeholder-for-local-dev"
AUTH_GITHUB_SECRET="placeholder-for-local-dev"

# OAuth JWT
OAUTH_JWT_SECRET="local-dev-jwt-secret"
OAUTH_REFRESH_TOKEN_EXPIRY_SECONDS=2592000
OAUTH_ACCESS_TOKEN_EXPIRY_SECONDS=3600
CONTROLENV
  }
  envsubst_control
  echo "[2/5] Created packages/app/control/.env"
fi

# ------------------------------------------------------------------
# 4. Create .env for echo-server (if missing)
# ------------------------------------------------------------------

if [ -f "$SERVER_DIR/.env" ]; then
  echo "[3/5] packages/app/server/.env already exists, skipping"
else
  cat > "$SERVER_DIR/.env" << 'SERVERENV'
# Echo Server - Local Development
# Generated by: pnpm setup

PORT=3069

# Database (same Postgres as control)
DATABASE_URL="postgresql://echo_user:echo_password@localhost:5469/echo_control_v2?schema=public"

# Control Plane
ECHO_CONTROL_BASE_URL=http://localhost:3000/

# Provider API Keys - uncomment and fill in to use real LLMs
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GEMINI_API_KEY=...
# OPENROUTER_API_KEY=...

# OAuth (must match control's OAUTH_JWT_SECRET)
OAUTH_JWT_SECRET="local-dev-jwt-secret"
SERVERENV
  echo "[3/5] Created packages/app/server/.env"
fi

# ------------------------------------------------------------------
# 5. Start PostgreSQL via Docker
# ------------------------------------------------------------------

echo "[4/5] Starting PostgreSQL container..."
cd "$CONTROL_DIR"
$DOCKER_COMPOSE -f docker-local-db.yml up -d 2>&1 | sed 's/^/       /'

echo "       Waiting for PostgreSQL..."
for i in $(seq 1 30); do
  if docker exec echo-control-postgres-v2 pg_isready -U echo_user -d echo_control_v2 &> /dev/null; then
    break
  fi
  sleep 1
done

if docker exec echo-control-postgres-v2 pg_isready -U echo_user -d echo_control_v2 &> /dev/null; then
  echo "       PostgreSQL is ready."
else
  echo "       WARNING: PostgreSQL might not be ready yet, but continuing..."
fi

# ------------------------------------------------------------------
# 6. Run Prisma generate + migrate
# ------------------------------------------------------------------

echo "[5/5] Running Prisma migrations..."
cd "$CONTROL_DIR"
pnpm exec prisma generate 2>&1 | tail -1 | sed 's/^/       /'
pnpm exec prisma migrate deploy 2>&1 | tail -3 | sed 's/^/       /' || \
  pnpm exec prisma db push 2>&1 | tail -3 | sed 's/^/       /'

cd "$ROOT_DIR"

echo ""
echo "=== Setup complete! ==="
echo ""
echo "Run:  pnpm dev"
echo ""
echo "  Echo Control  ->  http://localhost:3000"
echo "  Echo Server   ->  http://localhost:3069"
echo ""
echo "To use real LLM providers, add API keys to packages/app/server/.env"
echo ""
