#!/bin/bash
set -e

# Echo Control - local environment setup
# Generates a .env with sensible defaults for local development.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTROL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$CONTROL_DIR"

# Generate AUTH_SECRET if not already in .env
if [ -f .env ] && grep -q "^AUTH_SECRET=" .env; then
    echo "AUTH_SECRET already exists in .env, skipping generation."
else
    echo "Generating AUTH_SECRET..."
    AUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")

    if [ -f .env ]; then
        echo "AUTH_SECRET=$AUTH_SECRET" >> .env
        echo "Appended AUTH_SECRET to existing .env"
    else
        cat > .env << ENVEOF
# Echo Control - Local Development
# Generated by: pnpm local-setup

ECHO_CONTROL_APP_BASE_URL="http://localhost:3000"
API_KEY_PREFIX="echo_"

DATABASE_URL="postgresql://echo_user:echo_password@localhost:5469/echo_control_v2?schema=public"

AUTH_SECRET="$AUTH_SECRET"

AUTH_GOOGLE_ID="placeholder-for-local-dev"
AUTH_GOOGLE_SECRET="placeholder-for-local-dev"
AUTH_GITHUB_ID="placeholder-for-local-dev"
AUTH_GITHUB_SECRET="placeholder-for-local-dev"

OAUTH_JWT_SECRET="local-dev-jwt-secret"
OAUTH_REFRESH_TOKEN_EXPIRY_SECONDS=2592000
OAUTH_ACCESS_TOKEN_EXPIRY_SECONDS=3600
ENVEOF
        echo "Created .env with all local defaults."
    fi
fi

# Make sure DATABASE_URL is set
if [ -f .env ] && grep -q "^DATABASE_URL=" .env; then
    echo "DATABASE_URL already exists in .env."
else
    echo 'DATABASE_URL="postgresql://echo_user:echo_password@localhost:5469/echo_control_v2?schema=public"' >> .env
    echo "Added DATABASE_URL to .env."
fi

echo ""
echo "Setup complete! Next steps:"
echo "  1. Start Postgres:  docker compose -f docker-local-db.yml up -d"
echo "  2. Run migrations:  pnpm exec prisma generate && pnpm exec prisma migrate deploy"
echo "  3. Start dev:       pnpm dev"
echo ""
echo "Or from the repo root, just run: pnpm setup"
